"""update order table

Revision ID: 035f49693a81
Revises: 3f012e5b29ad
Create Date: 2022-08-01 13:52:55.044978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '035f49693a81'
down_revision = '3f012e5b29ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('master_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_order_master_id'), 'order', ['master_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_master_id'), table_name='order')
    op.drop_column('order', 'master_id')
    # ### end Alembic commands ###
