"""add version table

Revision ID: 1ffc67b64581
Revises: 96d8f0c2febd
Create Date: 2022-08-19 14:38:43.552341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ffc67b64581'
down_revision = '96d8f0c2febd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_order_product_id', table_name='order')
    op.create_foreign_key(None, 'order', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.create_index('ix_order_product_id', 'order', ['product_id'], unique=False)
    # ### end Alembic commands ###
