"""add mpcode table1

Revision ID: 3f012e5b29ad
Revises: a0583646fb2a
Create Date: 2022-07-29 11:01:14.364551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f012e5b29ad'
down_revision = 'a0583646fb2a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mpcode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('request_time', sa.Integer(), nullable=False),
    sa.Column('expire_time', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mpcode_expire_time'), 'mpcode', ['expire_time'], unique=False)
    op.create_index(op.f('ix_mpcode_id'), 'mpcode', ['id'], unique=False)
    op.create_index(op.f('ix_mpcode_phone'), 'mpcode', ['phone'], unique=False)
    op.create_index(op.f('ix_mpcode_request_time'), 'mpcode', ['request_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mpcode_request_time'), table_name='mpcode')
    op.drop_index(op.f('ix_mpcode_phone'), table_name='mpcode')
    op.drop_index(op.f('ix_mpcode_id'), table_name='mpcode')
    op.drop_index(op.f('ix_mpcode_expire_time'), table_name='mpcode')
    op.drop_table('mpcode')
    # ### end Alembic commands ###
