"""add desc to master table

Revision ID: 571d516728a9
Revises: d97ddbd6e43f
Create Date: 2022-08-18 17:40:41.909563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '571d516728a9'
down_revision = 'd97ddbd6e43f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master', sa.Column('desc', sa.String(), nullable=True, comment='老师介绍'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('master', 'desc')
    # ### end Alembic commands ###
