"""add mpcode table

Revision ID: 5e445effe416
Revises: c89603f3e472
Create Date: 2022-07-29 10:37:50.354939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e445effe416'
down_revision = 'c89603f3e472'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
