"""add create_time for order table

Revision ID: 6864b0d05fe4
Revises: bf29f2a0b0ba
Create Date: 2022-08-05 11:05:54.868827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6864b0d05fe4'
down_revision = 'bf29f2a0b0ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'))
    op.create_index(op.f('ix_order_create_time'), 'order', ['create_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_create_time'), table_name='order')
    op.drop_column('order', 'create_time')
    # ### end Alembic commands ###
