"""add create_time to user table

Revision ID: 89f590e49f79
Revises: a51c3f56ec55
Create Date: 2022-08-17 10:56:27.230387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89f590e49f79'
down_revision = 'a51c3f56ec55'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'))
    op.create_index(op.f('ix_user_create_time'), 'user', ['create_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_create_time'), table_name='user')
    op.drop_column('user', 'create_time')
    # ### end Alembic commands ###
