"""add pay_time for order table

Revision ID: 9f65928163b3
Revises: 5b96290d5336
Create Date: 2022-08-18 13:57:04.178517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f65928163b3'
down_revision = '5b96290d5336'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('pay_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='支付时间'))
    op.create_index(op.f('ix_order_pay_time'), 'order', ['pay_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_pay_time'), table_name='order')
    op.drop_column('order', 'pay_time')
    # ### end Alembic commands ###
