"""Add column avatar for master table

Revision ID: a51c3f56ec55
Revises: 6864b0d05fe4
Create Date: 2022-08-16 09:58:35.714807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a51c3f56ec55'
down_revision = '6864b0d05fe4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master', sa.Column('avatar', sa.String(), nullable=True, comment='头像'))
    op.add_column('order', sa.Column('divination', sa.String(), nullable=True))
    op.drop_index('ix_order_master', table_name='order')
    op.drop_column('order', 'master')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('master', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_order_master', 'order', ['master'], unique=False)
    op.drop_column('order', 'divination')
    op.drop_column('master', 'avatar')
    # ### end Alembic commands ###
