"""add url to version table

Revision ID: ab3c5cc144a8
Revises: 7c38943849a8
Create Date: 2022-08-19 16:00:32.690535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab3c5cc144a8'
down_revision = '7c38943849a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('version', sa.Column('url', sa.String()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('version', 'url')
    # ### end Alembic commands ###
