"""add status for order table

Revision ID: bf29f2a0b0ba
Revises: eaaed700f62c
Create Date: 2022-08-05 10:25:22.108111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf29f2a0b0ba'
down_revision = 'eaaed700f62c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('status', sa.Integer(), nullable=True, comment='状态：0 - 未确认, 1 - 已支付, 2 - 已确认, 3 - 作废'))
    op.alter_column('order', 'amount',
               existing_type=sa.INTEGER(),
               comment="金额，单位'分'",
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'amount',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment="金额，单位'分'",
               existing_nullable=True)
    op.drop_column('order', 'status')
    # ### end Alembic commands ###
