"""add more info to order table

Revision ID: d97ddbd6e43f
Revises: 9f65928163b3
Create Date: 2022-08-18 16:13:22.545659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd97ddbd6e43f'
down_revision = '9f65928163b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('name', sa.String(), nullable=True))
    op.add_column('order', sa.Column('sex', sa.Integer(), nullable=True))
    op.add_column('order', sa.Column('birthday', sa.String(), nullable=True))
    op.add_column('order', sa.Column('location', sa.String(), nullable=True))
    op.create_index(op.f('ix_order_location'), 'order', ['location'], unique=False)
    op.create_index(op.f('ix_order_name'), 'order', ['name'], unique=False)
    op.create_index(op.f('ix_order_sex'), 'order', ['sex'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_sex'), table_name='order')
    op.drop_index(op.f('ix_order_name'), table_name='order')
    op.drop_index(op.f('ix_order_location'), table_name='order')
    op.drop_column('order', 'location')
    op.drop_column('order', 'birthday')
    op.drop_column('order', 'sex')
    op.drop_column('order', 'name')
    # ### end Alembic commands ###
