"""add reason to order table

Revision ID: df2c73988d8d
Revises: b19bb0a47767
Create Date: 2022-08-22 10:53:41.373031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df2c73988d8d'
down_revision = 'b19bb0a47767'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('reason', sa.String(), nullable=True))
    op.alter_column('order', 'arrange_status',
               existing_type=sa.INTEGER(),
               comment='排盘状态：0 - 未排盘, 1 - 待审核, 2 - 拒绝, 3 - 完成',
               existing_comment='排盘状态：0 - 未排盘, 1 - 已排盘',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'arrange_status',
               existing_type=sa.INTEGER(),
               comment='排盘状态：0 - 未排盘, 1 - 已排盘',
               existing_comment='排盘状态：0 - 未排盘, 1 - 待审核, 2 - 拒绝, 3 - 完成',
               existing_nullable=True)
    op.drop_column('order', 'reason')
    # ### end Alembic commands ###
