"""Add master table

Revision ID: eaaed700f62c
Revises: 035f49693a81
Create Date: 2022-08-03 15:27:18.684279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaaed700f62c'
down_revision = '035f49693a81'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('rate', sa.Integer(), nullable=False, comment='分成比例'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('order_number', sa.Integer(), nullable=True, comment='订单数量'),
    sa.Column('status', sa.Integer(), nullable=True, comment='状态: 0 - 未激活, 1 - 激活, 2 - 失效, 3 - 待激活'),
    sa.Column('order_amount', sa.Integer(), nullable=True, comment='订单金额'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_create_time'), 'master', ['create_time'], unique=False)
    op.create_index(op.f('ix_master_id'), 'master', ['id'], unique=False)
    op.create_index(op.f('ix_master_name'), 'master', ['name'], unique=True)
    op.create_index(op.f('ix_master_phone'), 'master', ['phone'], unique=True)
    op.create_index(op.f('ix_master_status'), 'master', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_master_status'), table_name='master')
    op.drop_index(op.f('ix_master_phone'), table_name='master')
    op.drop_index(op.f('ix_master_name'), table_name='master')
    op.drop_index(op.f('ix_master_id'), table_name='master')
    op.drop_index(op.f('ix_master_create_time'), table_name='master')
    op.drop_table('master')
    # ### end Alembic commands ###
